apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: demo-rhdh-collection3
  description: A collection of Golden path templates for Red Hat Developer Hub
spec:
  targets:
    - https://raw.githubusercontent.com/YogiSoni-lazy/RHDH-Golden-Path-Template/main/templates/spring-boot-app/template.yaml

