---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.repoName }}-tekton-ci
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: "https://github.com/${{ values.orgName }}/${{ values.repoName }}.git"
    path: tekton
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
